"""Generate static, indexable RU/KZ/EN pages. Python standard library only."""
from pathlib import Path
import json, html, shutil, re
P=Path(__file__).resolve().parents[1]
D=json.loads((P/'content/translations.json').read_text()); projects=json.loads((P/'content/projects.json').read_text())
E=html.escape
ORIGIN='https://sabir2025.github.io/rakishov' # Change before publishing on another domain.
def image(p):
 i=p['index']; color=p['color']; name=p['name']
 shapes=['''<path d="M510 520V200L715 120V440Z" fill="#a9b19e"/><path d="M715 120L860 195V510L715 440Z" fill="#515d4c"/><path d="M542 520V245L570 230V505M600 491V215L628 200V477M660 462V185L688 170V448" stroke="#eff0e7" stroke-width="9"/>''', '''<ellipse cx="700" cy="515" rx="160" ry="22" fill="#b49170" opacity=".4"/><path d="M596 294Q700 245 799 294L780 415Q700 449 616 415Z" fill="#d36537"/><path d="M615 295V167Q700 138 785 167L799 294" fill="#bc512b"/><path d="M628 408L612 513M770 407L790 513" stroke="#70432b" stroke-width="14"/><path d="M610 188Q700 165 781 188" fill="none" stroke="#f4b388" stroke-width="2"/>''', '''<circle cx="704" cy="316" r="157" fill="#151a15"/><circle cx="704" cy="316" r="121" fill="none" stroke="#d2f34b" stroke-width="2"/><path d="M600 316H652L684 249L724 388L755 302H810" fill="none" stroke="#d2f34b" stroke-width="10" stroke-linecap="round"/><circle cx="703" cy="138" r="10" fill="#171a17"/>''', '''<rect x="450" y="135" width="420" height="377" rx="8" fill="#f9f9f6"/><rect x="470" y="159" width="380" height="55" rx="3" fill="#eeeef3"/><rect x="482" y="175" width="130" height="8" fill="#686278"/><rect x="482" y="191" width="75" height="5" fill="#b5b1c0"/><rect x="474" y="241" width="112" height="231" fill="#e8e7ef"/><rect x="601" y="241" width="112" height="231" fill="#e9efd9"/><rect x="728" y="241" width="112" height="231" fill="#eee0d5"/><g fill="#fff"><rect x="483" y="280" width="94" height="68"/><rect x="483" y="360" width="94" height="68"/><rect x="610" y="280" width="94" height="96"/><rect x="737" y="280" width="94" height="58"/></g><g stroke="#928da0" stroke-width="4"><path d="M493 300h58m-58 15h34m117-15h57m-57 15h37m-162 67h55m199-79h57"/></g>''', '''<g fill="none" stroke-width="5"><path d="M573 130C857 240 551 405 807 509" stroke="#bb4d35"/><path d="M801 130C517 240 823 405 567 509" stroke="#719079"/></g>'''+''.join(f'<path d="M{575+int(95*(1+__import__("math").sin(y/58)))} {y}H{805-int(95*(1+__import__("math").sin(y/58)))}" stroke="#e79f85" stroke-width="3"/>' for y in range(152,510,19)), '''<g stroke="#8a9694" stroke-width="2"><path d="M500 427L705 320L862 391L660 510Z" fill="#e3e6e3"/><path d="M500 427V459L660 544V510Z" fill="#929d99"/><path d="M660 510L862 391V423L660 544Z" fill="#61726d"/><path d="M500 337L705 230L862 301L660 420Z" fill="#eff1ed"/><path d="M500 337V369L660 454V420Z" fill="#a5aeaa"/><path d="M660 420L862 301V333L660 454Z" fill="#73827c"/><path d="M500 247L705 140L862 211L660 330Z" fill="#f8f9f5"/><path d="M500 247V279L660 364V330Z" fill="#aeb7b2"/><path d="M660 330L862 211V243L660 364Z" fill="#84938b"/></g>''']
 # Original vector concept artwork; no external image assets or fabricated screenshots.
 svg=f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 960 640"><rect width="960" height="640" fill="{color}"/><rect x="42" y="42" width="876" height="556" rx="5" fill="#f8f7f2"/><path d="M42 101H918" stroke="#ddded5"/><text x="75" y="79" font-family="Arial,sans-serif" font-size="20" font-weight="700" fill="#20251e">{name}</text><path d="M847 65H882M847 73H882M847 81H882" stroke="#20251e" stroke-width="2"/><text x="75" y="224" font-family="Arial,sans-serif" font-weight="700" font-size="57" fill="#20251e">{name.split()[0]}</text><text x="75" y="283" font-family="Arial,sans-serif" font-weight="700" font-size="57" fill="#20251e">{('01—06','FORM.','BEAT.','SPACE.','NOVA.','SOLID.')[i]}</text><g fill="#92988b"><rect x="77" y="328" width="245" height="7"/><rect x="77" y="348" width="207" height="7"/><rect x="77" y="368" width="167" height="7"/></g><rect x="76" y="424" width="167" height="47" fill="#20251e"/><path d="M196 447H221m-8-8 9 8-9 8" fill="none" stroke="#f8f7f2" stroke-width="2"/>{shapes[i]}<text x="76" y="561" font-family="monospace" font-size="12" fill="#626c5d">SR / 0{i+1}</text></svg>'''
 (P/f'assets/images/{p["slug"]}.svg').write_text(svg)
for p in projects:image(p)
for lang in D:
 t=D[lang]
 def s(k,tag='span',cls=''):return f'<{tag} data-t="{k}"'+(f' class="{cls}"' if cls else '')+'>'+E(t[k]).replace('\n','<br>')+f'</{tag}>'
 def attr(k):return E(t[k],quote=True)
 loc='' if lang=='kz' else lang+'/'
 def render(kind,pr=None):
  route='' if kind=='home' else ('work/'+pr['slug']+'/' if kind=='case' else 'analytics/'+('leads/' if kind=='leads' else 'login/' if kind=='login' else ''))
  directory=P/loc/route;directory.mkdir(parents=True,exist_ok=True)
  depth=len((loc+route).strip('/').split('/')) if loc+route else 0
  root='../'*depth or './'; home=root+loc
  title=('Sabir Rakishov — '+t['role']) if kind=='home' else (pr['name']+' — '+t['title'+str(pr['index'])] if kind=='case' else 'Sabir Analytics — '+t['owner'])
  desc=t['intro'] if kind!='case' else t['tagline'+str(pr['index'])]
  nav=''.join(f'<a href="{home}#{id}" data-home="#{id}"><small>0{i+1}</small>{s(k)}<span aria-hidden="true">↗</span></a>' for i,(id,k) in enumerate([('work','work'),('services','services'),('process','process'),('about','about'),('faq','faq'),('contact','start')]))
  langs='<div class="languages" aria-label="Language">'+''.join(f'<button type="button" data-lang="{l}" aria-pressed="{str(l==lang).lower()}">{l.upper()}</button>' for l in ['kz','ru','en'])+'</div>'
  brand=f'<a class="brand" href="{home}" data-home=""><span class="logo-mark"><img src="{root}assets/logo.svg" width="84" height="42" alt="Sabir Rakishov"></span></a>'
  header=f'<a class="skip" href="#main">{s("skip")}</a><header class="header">{brand}<div class="header-right">{langs}<button class="burger" type="button" aria-label="{attr("menu")}" data-label="menu" aria-expanded="false" aria-controls="navigation"><span></span><span></span><span></span></button></div></header><dialog id="navigation" class="navigation" aria-label="{attr("menu")}"><div class="nav-head">{brand}<button class="nav-close" aria-label="{attr("close")}" data-label="close">×</button></div><nav>{nav}</nav><div class="nav-bottom">{s("location")}<div><a href="https://wa.me/77022950040" data-event="whatsapp_click">WhatsApp ↗</a><a href="https://t.me/rakishovbot" data-event="telegram_click">Telegram ↗</a></div></div></dialog>'
  footer=f'<footer class="footer"><div class="eyebrow">{s("location")}</div>{s("footerTitle","h2")}<a class="footer-cta" href="{home}#contact" data-home="#contact">{s("start")} ↗</a><div class="footer-bottom">{brand}<div><a href="tel:+77022950040">+7 702 295 00 40</a><a href="https://wa.me/77022950040" data-event="whatsapp_click">WhatsApp ↗</a><a href="https://t.me/rakishovbot" data-event="telegram_click">Telegram ↗</a></div></div><div class="copyright"><span>© 2026 Sabir Rakishov</span>{s("rights")}</div></footer>'
  if kind=='home':
   cards=''.join(f'<a class="project project-{i}" href="{home}work/{p["slug"]}/" data-route="work/{p["slug"]}/" data-project="{p["slug"]}"><div class="project-image" style="--project-color:{p["color"]}"><img src="{root}assets/images/{p["slug"]}.svg" alt="{E(p["name"])}" width="960" height="640" loading="lazy"><span class="round-arrow" aria-hidden="true">↗</span></div><div class="project-caption"><div><h3>{p["name"]}</h3>{s("title"+str(i))}</div><span class="project-kind">{s("concept")} / 0{i+1}</span></div></a>' for i,p in enumerate(projects))
   services=''.join(f'<details class="service"><summary><span class="mono">0{i+1}</span>{s("s"+str(i),"h3")}<span class="plus" aria-hidden="true">↗</span></summary>{s("sd"+str(i),"p")}</details>' for i in range(4))
   steps=''.join(f'<div class="process-step"><span class="mono">0{i+1}</span><div>{s("p"+str(i),"h3")}{s("pd"+str(i),"p")}</div></div>' for i in range(8))
   faq=''.join(f'<details class="faq-row"><summary>{s("q"+str(i))}<span class="plus" aria-hidden="true">+</span></summary>{s("a"+str(i),"p")}</details>' for i in range(6))
   main=f'''<main id="main"><section class="hero" id="home"><canvas id="field" aria-hidden="true"></canvas><h1 class="hero-usp">{s('heroLead')}<br>{s('heroFinish')}</h1><div class="hero-bottom"><div>{s('intro','p')}<div class="hero-actions"><a class="btn" href="#contact" data-event="cta_click">{s('start')} <span>↗</span></a><a class="underlink" href="#work">{s('view')} ↓</a></div></div></div><div class="hero-foot">{s('role')}<a href="#approach">{s('scroll')} ↓</a></div></section>
<section class="manifest section" id="approach"><div class="eyebrow">{s('manifestLabel')}</div>{s('manifest','h2')}<div class="manifest-end"><span class="cross" aria-hidden="true">↗</span>{s('manifestDesc','p')}</div></section>
<section class="section works" id="work"><div class="section-head"><div><div class="eyebrow">02 / {s('work')}</div>{s('selected','h2')}</div>{s('workNote','p')}</div><div class="projects">{cards}</div></section>
<section class="section services" id="services"><div class="section-head"><div><div class="eyebrow">03 / {s('services')}</div>{s('directions','h2')}</div></div>{services}</section>
<section class="section process" id="process"><div class="process-heading"><div class="eyebrow">04 / {s('process')}</div>{s('processTitle','h2')}</div><div class="process-list">{steps}</div></section>
<section class="section about" id="about"><div class="portrait"><img src="{root}assets/images/author.webp" width="600" height="750" alt="Сабир Ракишов" loading="lazy"></div><div class="about-copy"><div class="eyebrow">05 / {s('about')}</div>{s('aboutTitle','h2')}{s('aboutText','p')}<a class="underlink" href="https://wa.me/77022950040" data-event="whatsapp_click">{s('start')} ↗</a></div></section>
<section class="tech-strip"><span class="eyebrow">{s('tools')}</span><div>Figma / UI / UX</div><div>HTML / CSS / JavaScript</div><div>API / PostgreSQL / Git</div></section>
<section class="section faq" id="faq"><div><div class="eyebrow">06 / {s('faq')}</div>{s('faqTitle','h2')}</div><div>{faq}</div></section>
<section class="section contact" id="contact"><div><div class="eyebrow">{s('start')}</div>{s('contactTitle','h2')}{s('contactDesc','p')}<div class="contact-links"><a class="underlink" href="https://wa.me/77022950040" data-event="whatsapp_click">WhatsApp ↗</a><a class="underlink" href="https://t.me/rakishovbot" data-event="telegram_click">Telegram ↗</a></div></div><div id="project-form" class="project-form"><noscript>{t['offline']} <a href="https://wa.me/77022950040">WhatsApp</a></noscript></div></section><section class="privacy"><details><summary>{s('privacy')}</summary>{s('privacyText','p')}</details></section></main>'''
  elif kind=='case':
   i=pr['index'];nxt=projects[(i+1)%len(projects)]
   main=f'''<main id="main" class="case"><div class="case-top"><a class="underlink" href="{home}#work" data-home="#work">← {s('allwork')}</a><span class="mono">0{i+1} / 06</span></div><div class="case-heading"><div><div class="eyebrow">{s('concept')} / 2026</div><h1>{pr['name']}</h1>{s('title'+str(i),'p')}</div>{s('tagline'+str(i),'p')}</div><img class="case-cover" src="{root}assets/images/{pr['slug']}.svg" width="960" height="640" alt="{pr['name']}"><p class="case-note">{s('caseNote')}</p><section class="case-section"><h2>01 / {s('task')}</h2>{s('task'+str(i),'p')}</section><section class="case-section"><h2>02 / {s('approach')}</h2>{s('structure'+str(i),'p')}</section><section class="case-section"><h2>03 / {s('visual')}</h2>{s('visual'+str(i),'p')}</section><div class="case-colors" style="--project-color:{pr['color']}"><div>{pr['color']}</div><div>#151515</div><div>#F5F4EF</div></div><section class="case-section"><h2>04 / {s('mobile')}</h2><div class="mobile-concept" style="--project-color:{pr['color']}"><div class="phone-top">{pr['name']} <span>≡</span></div>{s('tagline'+str(i),'h3')}<img src="{root}assets/images/{pr['slug']}.svg" width="960" height="640" loading="lazy" alt="{pr['name']}"><div class="phone-lines"></div></div></section><section class="case-section"><h2>05 / {s('result')}</h2><div>{s('caseResult','p')}{s('caseStack','p')}</div></section><a class="next-project" href="{home}work/{nxt['slug']}/" data-route="work/{nxt['slug']}/">{s('nextProject')}<strong>{nxt['name']} ↗</strong></a></main>'''
  admin=False
  url=ORIGIN+'/'+loc+route
  alternates=''.join(f'<link rel="alternate" hreflang="{("kk" if l=="kz" else l)}" href="{ORIGIN}/{("" if l=="kz" else l+"/")}{route}">' for l in D)
  page=f'''<!doctype html><html lang="{'kk' if lang=='kz' else lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{E(title)}</title><meta name="description" content="{E(desc,quote=True)}"><meta name="theme-color" content="#f5f4ef"><meta name="robots" content="{'noindex,nofollow' if admin else 'index,follow'}"><link rel="canonical" href="{url}">{alternates}<meta property="og:title" content="{E(title,quote=True)}"><meta property="og:description" content="{E(desc,quote=True)}"><meta property="og:type" content="website"><meta property="og:url" content="{url}"><meta name="twitter:card" content="summary"><link rel="icon" type="image/svg+xml" sizes="any" href="{root}assets/favicon.svg?v=3"><link rel="stylesheet" href="{root}css/site.css">{('<link rel="stylesheet" href="'+root+'css/admin.css">') if admin else ''}<script defer src="{root}js/settings.js"></script><script defer data-sr-app src="{root}js/site.bundle.js"></script></head><body data-root="{root}" data-lang="{lang}" data-page="{kind}" data-route="{route}" {('data-project="'+pr['slug']+'"') if pr else ''} class="{'admin' if admin else ''}">{header}{main}{'' if admin else footer}<aside id="consent-banner" class="consent-banner" hidden>{s('analyticsConsent','p')}<div><button data-consent="yes" class="btn">{s('allow')}</button><button data-consent="no" class="text-btn">{s('decline')}</button></div></aside><button id="back-to-top" class="back-to-top" type="button" aria-label="{attr('backToTop')}" data-label="backToTop" hidden><span aria-hidden="true">↑</span></button><div id="toast" class="toast" role="status" hidden></div></body></html>'''
  if not admin:
   schema={'@context':'https://schema.org','@type':'Person','name':'Sabir Rakishov','url':ORIGIN+'/','jobTitle':t['role'],'sameAs':['https://t.me/rakishovbot']}
   page=page.replace('</head>','<script type="application/ld+json">'+json.dumps(schema)+'</script></head>')
  (directory/'index.html').write_text(page)
 for kind in ['home']:render(kind)
 for pr in projects:render('case',pr)
urls=[ORIGIN+'/'+('' if l=='kz' else l+'/')+r for l in D for r in ['']+['work/'+p['slug']+'/' for p in projects]]
(P/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join('<url><loc>'+u+'</loc></url>' for u in urls)+'</urlset>')
(P/'robots.txt').write_text('User-agent: *\nAllow: /\n'+''.join('Disallow: /'+('' if l=='kz' else l+'/')+'analytics/\n' for l in D)+'Sitemap: '+ORIGIN+'/sitemap.xml\n')
(P/'404.html').write_text('<!doctype html><html lang="ru"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>404 — Sabir Rakishov</title><link rel="icon" type="image/svg+xml" href="assets/favicon.svg?v=3"><body style="font:24px sans-serif;background:#f5f4ef;padding:10vw"><h1>404</h1><p>Страница не найдена / Page not found</p><a href="'+ORIGIN+'/">Sabir Rakishov →</a></body></html>')
print('Generated 21 public pages and original vector previews.')
